-- Generated by nwg-displays on 2026-06-20 at 18:00:12. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1366x768@60.06",
    position = "554x1214",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@240.0",
    position = "0x134",
    scale = 1.0
})
